### ISSUE TITLE
Submit button is drawn over colour string input

### ISSUE THREAD

**Issue by psyren89** [Pes8/android-material-color-picker-dialog#1]
Using version 1.0.1, showing picker as a dialogue.
![image](https://cloud.githubusercontent.com/assets/2491530/9652137/219501a0-524b-11e5-8396-df2c257505df.png)

**Comment by Pes8** [comment]
Thanks for the report! Which kind of android do you use ?
Tomorrow I'll fix it

**Comment by psyren89** [comment]
Using a Nexus 7 2013 emulator, API22.

**Comment by Pes8** [comment]
I can't reproduce this bug. I have changed some xml settings. Please check if the bug persist. (add the last version of the library to the dependencies)

Thanks :)

**Comment by epm157** [comment]
Unfortunately this error is still there:
![screen shot 2015-09-28 at 11 54 26](https://cloud.githubusercontent.com/assets/4679569/10132682/0b7c8848-65d8-11e5-8213-ac4395fea5e6.png)

**Comment by Pes8** [comment]
@epm157  Wich Device/Android version do you have ?

I'll investigate more on this bug

**Comment by epm157** [comment]
I tested it on Nexus 5 with official 5.1 and Galaxy S3 custom 5.1.
It seems that the bug is related to last version of android so I decided to hide hexcode EditText and hashtag sigh TextView.

**Comment by Pes8** [comment]
@epm157 @psyren89  I tried to reproduce this bug but I really can't. I tried with a Nexus with 5.1, Nexus 7 emulator with API22, OnePlus One with 5.1.1, Samsung S6 Emulator, Samgung S6 Edge emulator and others. :(

I'm sorry but until I can reproduce it I can't solve it

**Comment by hemalrathod** [comment]
I am getting color value as integer in 8 digits. How do it get a hex color value as string?

**Comment by Pes8** [comment]
@hemalrathod It's not related with this issue .. Anyway you can convert it liek this:

`String hexColor = String.format("#%06X", (0xFFFFFF & intColor));`

Where intColor is the integer returned from the library :)

**Comment by hemalrathod** [comment]
Ok I got it the other way

`String hexColor = Integer.toHexString(intColor);`
