### ISSUE TITLE
How to get HEX value?

### ISSUE THREAD

**Issue by nicks258** [Pes8/android-material-color-picker-dialog#14]
From the callback i am getting a int value like -5089256 so how can i convert or get HEX value . Thanks :-)

**Comment by Pes8** [comment]
Hi, this is not an issue :) Anyway, there are several ways to do it:

`String hexColor = String.format("#%06X", (0xFFFFFF & intColor));`
or
`String hexColor = Integer.toHexString(intColor);`

Maybe I can add this as an example in the Readme but is not related with the color picker :)
