### ISSUE TITLE
In landscape, the hex value does not fit the EditText view

### ISSUE THREAD

**Issue by psyren89** [Pes8/android-material-color-picker-dialog#2]
Using version 1.0.1, opening as a dialogue.
![image](https://cloud.githubusercontent.com/assets/2491530/9652142/2fa9235c-524b-11e5-83e1-55474562c543.png)

**Comment by Pes8** [comment]
Thanks, I'll fix it tomorrow :)

**Comment by Pes8** [comment]
It should be fixed now :) new version 1.0.2
