### ISSUE TITLE
The callback doesnt work

### ISSUE THREAD

**Issue by AviadKlein10** [Pes8/android-material-color-picker-dialog#20]
Hi thank you for the library. But please fix the callback

Thank you

**Comment by Pes8** [comment]
Hi, can you explain and send more details ? Why should not work ?

**Comment by AviadKlein10** [comment]
Wow very fast!
Yes, when I hit the selected button nothing happen. I also try the
1.1version

בתאריך 3 באוק' 2017 11:02,‏ "Simone Pessotto" <notifications@github.com>
כתב:

**Comment by Pes8** [comment]
Are you using the last version ? Did you tried the example in the readme ?

Please also provide some information about the device as os version, device trademark & model etc.

**Comment by AviadKlein10** [comment]
Of curse!
So the latest 1.2.0 version with the readme example wothout making cp
final.
I use the listener as the readme says.
Im using LG G4 version 6.0.0


בתאריך 3 באוק' 2017 11:11,‏ "Simone Pessotto" <notifications@github.com>
כתב:

Are you using the last version ? Did you tried the example in the readme ?

Please also provide some information about the device as os version, device
trademark & model etc.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Pes8/android-material-color-picker-dialog/issues/20#issuecomment-333771256>,
or mute the thread

**Comment by Pes8** [comment]
Ok, I'll investigate in the next 3-5 days. Thank you

**Comment by AviadKlein10** [comment]
Thank you for the quick replay and for the library. Tell me if you need me
to test it.
Good luck!

בתאריך 3 באוק' 2017 11:42,‏ "Simone Pessotto" <notifications@github.com>
כתב:

**Comment by anonym24** [comment]
yes, dialog doesn't disappear

**Comment by anonym24** [comment]
so it works, but dialog doesn't disappear

logs works:
```

                        Log.d("Alpha", Integer.toString(Color.alpha(color)));
                        Log.d("Red", Integer.toString(Color.red(color)));
                        Log.d("Green", Integer.toString(Color.green(color)));
                        Log.d("Blue", Integer.toString(Color.blue(color)));

                        Log.d("Pure Hex", Integer.toHexString(color));
                        Log.d("#Hex no alpha", String.format("#%06X", (0xFFFFFF & color)));
                        Log.d("#Hex with alpha", String.format("#%08X", (0xFFFFFFFF & color)));

```

**Comment by anonym24** [comment]
can be fixed by modifiying (in `ColorPicker.java`)

```
    private void sendColor() {
        if (callback != null)
            callback.onColorChosen(getColor());
    }
```

to

```
    private void sendColor() {
        if (callback != null)
            callback.onColorChosen(getColor());
        dismiss();
    }
```

**Comment by Pes8** [comment]
The dialog could be hided by simple call colorpicker.dimiss() inside the callback.

Anyway I have updated the library, now it's possible to enable the auto-close functionality by calling `colorPicker.enableAutoClose();`
