### ISSUE TITLE
Suggestion: Change the Colorpicker's values after initiation

### ISSUE THREAD

**Issue by Erlend2** [Pes8/android-material-color-picker-dialog#33]
Hello,

First of all, thank you for the wonderful color picker widget! It works very well.

I just miss one feature: To change the colorpicker's values (red, green, blue) after its initiation.

There are already the methods  `getAlpha`, `getRed`, `getGreen`, and `getBlue`. How about adding a `setColorAlpha`, `setRed`, `setGreen`, and `setBlue`? For instance:

```
Final ColorPicker cp = new ColorPicker(this);
cp.setAll(int, int, int, int); // With alpha
cp.setColors(int, int, int) // Without alpha
cp.setRed(int); cp.setGreen(int); cp.setBlue(int); // For each of the color values
```

This feature would be handy for pre-setting the colorpicker's values, e.g. when saving preferences.

**Comment by Pes8** [comment]
Hi! :) As I've mentioned in another issue I'm sorry but I don't have enough time for add feature to this little library.

I'm open to PR if someone want to collaborate :) It should be easy to add this feature

**Comment by Erlend2** [comment]
Hi again, I did some research on it and I think I've completed the code for it, though I'm not sure how to create the pull request.

**Comment by Pes8** [comment]
Thank you for the PR :) I'm closing the issue.
